config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
    root to: "users#new"
    resources :users
    
    resources :pictures do
        collection do
          post:confirm
        end
    end
    
    resources :sessions, only:[:new, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "letter_opener"
    end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    has_many :pictures, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_picture, through: :favorites, source: :picture
    
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_save { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    mount_uploader :image, ImageUploader
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのつぶやきをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(params[:picture_id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのつぶやきをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.order(id: :desc)
    @user = User.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    if params[:back]
        @picture = Picture.new(picture_params)
        if params[:cache][:image] != ""        
          @picture.image.retrieve_from_cache! params[:cache][:image]
        end
    else
        @picture = Picture.new
    end    
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    if @picture.save
      ContactMailer.contact_mail(@picture).deliver
      redirect_to  pictures_path      
    else
      render "new"
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    if @picture.update(picture_params)
        redirect_to pictures_path, notice: "編集が成功しました"
    else
        render "edit"
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
      redirect_to pictures_path, notice: "削除が成功しました"   
  end
  
  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render "new" if @picture.invalid?
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :description, :image_cache)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to new_user_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def login
    @user = User.new　
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @favorites_pictures = @user.favorite_picture
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_path
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to user_path(@user.id)
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_pictures_path 
    elsif action_name == "edit"
      
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sakegram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Sakegram</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if logged_in? %>
            <a class="navbar-brand" href="/pictures">Sakegram</a>
          <% else %>
            <a class="navbar-brand" href="/users/new">Sakegram</a>
          <% end %>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li><%= link_to "投稿", new_picture_path(current_user.id) %></li>
            <li><%= link_to "#{current_user.name}", user_path(current_user.id) %></li>
            <% else %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}, alert alert-danger text-center") %>
    <% end %>

    <%= yield %>

  <footer class="footer">
    <div class="container">
      <p class="footer-text">DIC-201803 HiranoMayumi</p>
    </div>
  </footer>    
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if picture.image.url == nil %>
        <div class="field">
            <strong class="top-font-color">画像を選択してください：</strong>
            <%= form.file_field :image, id: :feed_image %>
            <%= form.hidden_field :image_cache %>
        </div>
        <br>
    <% else %>
        <p>
          <strong class="top-font-color">画像</strong>
        </p>
        <p>
            <%= image_tag(picture.image) %>
            <%= form.file_field :image, id: :feed_image %>
            <%= form.hidden_field :image_cache %>
        </p>    
    <% end %>
  </div>
  
  
  <div class="field">
    <%= form.label :キャプション %><br>
    <div class="form-group">
      <div class="row">
      <div class="col-md-12">
      <%= form.text_area :description, id: :picture_description, :size=>"50x5" %>
      </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "シェアする", class: "btn btn-info col-md-offset-8 col-md-3 col-sm-offset-8 col-sm-3 col-xs-offset-8 col-xs-3" %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>以下の内容で投稿していいですか？</h4>
        </div>
    

        <div class="panel-body">
            <%= form_with(model:@picture, url:pictures_path, local:true) do |form| %>

                <%= image_tag(@picture.image, :class => "center-block") if @picture.image.url %>
                <%= form.hidden_field :image_cache %>
                <%= hidden_field_tag :"cache[image]",@picture.image.cache_name %>
                <%= form.hidden_field :description %>
                <p><%= @picture.description %></p>
                <div class="row">
                <br>
                <%= form.submit "シェアする", class: "btn btn-info col-md-offset-6 col-md-2" %>
            <% end %>
        
            <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
                <%= form.hidden_field :description %>
                <%= form.hidden_field :image %>
                <%= hidden_field_tag :"cache[image]",@picture.image.cache_name %>
                <%= form.submit "戻る", name: "back", class: "btn btn-info col-md-offset-1 col-md-2" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/pictures/edit.html.erb
<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3>投稿を編集する</h3>
        </div>    
        
        <div class="panel-body">    
            <%= render 'form', picture: @picture %>
        </div>
    </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  
  
  <h1>投稿一覧</h1>
    <% @pictures.each do |picture| %>
      <% user_id = @user.find(picture.user_id) %>
      <% name = user_id.name %>
      <table class="table table-bordered">
        <tr><td id="index-name"><%= name %></td></tr>
        <tr><td class="index-td" id="index-image"><%= image_tag(picture.image) %></td></tr>
        <tr><td class="index-td"><%= picture.description %></td></tr>
        <% if picture.user_id == current_user.id %>
          <tr><td class="index-td" id="index-action"><%= link_to 'edit', edit_picture_path(picture.id) %> | <%= link_to 'delete', picture_path(picture.id), method: :delete %></td></tr>
        <% else %>
          <tr><td class="index-td" id="index-action"><%= link_to 'いいね！', favorites_path(picture_id: picture.id), method: :post %> | <%= link_to 'いいねを解除する', favorite_path(picture.id), method: :delete  %>
          </td></tr>
        <% end %>
      </table>
    <% end %>
</div>

app/views/pictures/new.html.erb
<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3>写真を投稿する</h3>
        </div>    
        
        <div class="panel-body">    
            <%= render 'form', picture: @picture %>
        </div>
    </div>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @picture.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
    <tr>
      <td><%= form.label :name %></td>
      <td><%= form.text_field :name %></td>
    </tr>
  
    <tr>
      <td><%= form.label :email %></td>
      <td><%= form.text_field :email %></td>
    </tr>
  
    <tr>
      <td><%= form.label :password %></td>
      <td><%= form.password_field :password %></td>
    </tr>
    
    <tr>
      <td><%= form.label :password_confirmation %></td>
      <td><%= form.password_field :password_confirmation %></td>
    </tr>
  </table>

  <div class="field">
    <p>
      <strong>アイコン</strong>
    </p>
    <%= image_tag(@user.image.url) if @user.image.url %>
    <%= form.file_field :image, id: :feed_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <br>
  
  <div class="actions">
    <%= form.submit "登録する", {class:"btn btn-info"} %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <h1>マイページ編集</h1>
    
    <%= render 'form', user: @user %>
    
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= image_tag(user.image) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="container">
    <div class="col-md-7">
        <h1>Sakegram</h1>
        <h3>友達の写真をチェックしよう</h3>
        <%= render 'form', user: @user %>
    </div>
</div>

<div class="container">
    <div class="login">
        <h3>アカウントをお持ちですか？</h3>
        <%= link_to "ログインする" %>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="signin">
        <h1>Sakegram</h1>
        <h3>友達の写真をチェックしよう</h3>
        <%= render 'form', user: @user %>
    </div>

    <div class="login">
        <h3>アカウントをお持ちですか？</h3>
        <%= link_to "ログインする", new_session_path %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>マイページ</h1>
  
  <div class="row">
      
    <% if @user.image.url == nil %>
      <span class="glyphicon glyphicon-user iconsize col-md-4" aria-hidden="true"></span>
    <% else %>
      <%= image_tag(@user.image, :class => "col-md-4")%>
    <% end %>
    
    <table class="col-md-6">
      <tr>
        <td><strong>名前:</strong></td>
        <td><%= @user.name %></td>
      </tr>
      
      <tr>
        <td><strong>メールアドレス:</strong></td>
        <td><%= @user.email %></td>
      </tr>
    </table>
  </div>

  <%= link_to '編集', edit_user_path(@user), class:"btn btn-info col-md-offset-7" %>  
  <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"btn btn-info" %>
  
  <br>
  
  <h1>お気に入り</h1>
  <% @favorites_pictures.each do |fav| %>
    <table class="table">
        <tr><td id="index-name"><%= @users.find(fav.user_id).name %></td>
        <tr><td class="index-td" id="index-image"><%= image_tag(fav.image) %></td></tr>
        <tr><td class="index-td"><%= fav.description %></td></tr>
    </table>
  <% end %>
    

</div>